### ISSUE TITLE
Get node list commang

### ISSUE THREAD

**Issue by AviFix** [yepher/RaZBerry#2]
Hi,

I'm looking for hours.

Can you please tell me what is the hex command for getting all nodes (and their data) in the network?

Thanks a lot

Avi

**Comment by yepher** [comment]
I think it is:

```
{
            "FIELD_KEY": "3",
            "FIELD_NAME": "ASSOCIATION_REPORT",
            "FIELD_DESCRIPTION": "Association Report",
            "FIELD_PARAMETERS": [
              {
                "FIELD_KEY": "3",
                "FIELD_NAME": "Node ID(s)",
                "FIELD_TYPE": "ARRAY",
                "FIELD_TYPEhashcode": "5",
                "FIELD_ARRAY_ATTRIBUTES": {
                  "FIELD_KEY": "0",
                  "FIELD_IS_ASCII": "False",
                  "FIELD_LEN": "255"
                }
              },
```

**Comment by AviFix** [comment]
Hi,

Thank you for your quick reply.

I'm using jssc for communication with the serial port (z wave controller).

What would be the end command to send to the serial port
```
serialPort.writeBytes(...);
```

Thank You very much

Avi

**Comment by yepher** [comment]
I am not quite sure what you are asking. This project does not have any Java.

I expect if you look at RaZBerry/docs/SDS11060-7 Z-Wave Command Class Specification.pdf it may have the information you are seeking. There are several captures available in the project too. You can have a look to see what is sent and received to work out if your code is working.

If you have not already I think what you are doing is probably a lot more like OpenZWave project and they are very helpful over there.

**Comment by AviFix** [comment]
HI,

i meant' like there is a command to get a specific node information:
https://github.com/yepher/RaZBerry/blob/master/binarySwitchSamples.md

i' looking for the command to get a list off all the nodes.

Thanks a lot 

Avi

**Comment by Trinity92** [comment]
http://www.digiwave.dk/en/programming/device-discovery-in-z-wave/#more-759

I think this is what you're looking for. Just try and send the same byte sequence over the serial port using your preferred programming language.

**Comment by AviFix** [comment]
That is exactly what i was looking for.

Thank you all very much

Avi
